baseURL: https://david.gyttja.com
languageCode: en-us
title: gyttja
theme: etch
disableHugoGeneratorInject: true
enableRobotsTXT: true
enableEmoji: false
copyright: © 2010-2022
description: Basic personal site theme styled with minimal tachyons, syntax
  highlighting, and blog series configuration.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: native
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  titleEmoji: ":tada:"
  highlight:
    light: friendly
    dark: native
  twitter: dfuchslin
  menu:
    - name: posts
      url: /posts/
    - name: categories
      url: /categories/
    - name: about
      url: /about/

Permalinks:
  post: post/:slug
